Order payment account
payfunc/model pull request #269
Opened 2020-10-14 08:47 UTC by robinnedergard

2020-10-14 09:44 UTC, simonmika requested changes

2020-10-14 09:44 UTC, simonmika commented on Payment/Account/Creatable.ts
>  	token: authly.Token
Optional? Deprecated?

2020-10-14 09:44 UTC, simonmika commented on Payment/Account/index.ts
>  	token: authly.Token
Deprecated?

2020-10-14 09:44 UTC, simonmika commented on Payment/Account/index.ts
>  }
Retry schedule? Not now but in the next part.

2020-10-14 09:44 UTC, simonmika commented on Payment/Card/Creatable.ts
> +	account?: authly.Identifier
Not in Creatable? When would it be used?

2020-10-14 09:44 UTC, simonmika commented on Payment/Card/index.ts
> +	account?: string // Old orders exists with account as authly.Token although for new orders account should be of type authly.Identifier.
`authly.Token | authly.Identifier` // Token is deprecated.

2020-10-15 08:26 UTC, simonmika approved these changes

2020-10-15 08:26 UTC, simonmika commented on Payment/Card/Creatable.ts
> -	account?: string
Are we certain that nobody uses this?

2020-10-15 08:29 UTC, robinnedergard commented on Payment/Card/Creatable.ts
> -	account?: string
We did in backend, but only after internal conversion between payment type account -> card. I have an update almost ready to change that.

2020-10-15 08:29 UTC, simonmika commented on Payment/Card/Creatable.ts
> -	account?: string
@fredrikbryntesson Feel free to merge and go ahead with this but keep the above question in mind.

2020-10-15 08:33 UTC, robinnedergard commented on Payment/Card/Creatable.ts
> -	account?: string
Checked that the two I know could have used it, does use the correct way already (type: "account"), that will still work. Website information needs updating though.

2020-10-16 08:19 UTC, fredrikbryntesson approved these changes

2020-10-16 08:19 UTC, merged