added message propery to key
payfunc/model pull request #299
Opened 2020-11-04 13:31 UTC by robinnedergard

2020-11-05 08:51 UTC, fredrikbryntesson requested changes

2020-11-05 08:51 UTC, fredrikbryntesson commented on Key/Key.ts
>  	features?: flagly.Flags
What is the purpose?

2020-11-05 08:55 UTC, robinnedergard commented on Key/Key.ts
>  	features?: flagly.Flags
"message" is a url for message interface to send messages to merchants that want to handle receipts themselves.

2020-11-09 09:21 UTC, fredrikbryntesson approved these changes

2020-11-09 09:21 UTC, merged