Subscription
payfunc/model pull request #316
Opened 2020-12-02 15:26 UTC by florianebmeier

2020-12-02 16:03 UTC, simonmika requested changes

2020-12-02 16:03 UTC, simonmika commented on Balance.ts
> +		| number
Put a comment here defining if this would be the hard or the soft limit.

2020-12-02 16:03 UTC, simonmika commented on Balance.ts
> +export interface Balance {
Did we not decide for this to be merged into `Account`? Maybe put this in a separate PR?

2020-12-03 07:54 UTC, florianebmeier commented on Schedule/calculateDue.ts
> +	previousDue?: isoly.DateTime
We have two main reasons to give `previous`. 
1. To reduce computing power. We have the previous due date saved and just having it as an optional parameter will reduce load, because we do not have to calculate the previous steps or calculate a valid Due Date from `start`. 
2. To calculate multiple future dates as planned in the UI we need to calculate multiple dates in the future while ensuring that they are on the same schedule, i.e. have the same `start` of the curve. The simplest way to ensure that is to give the previous due date to the function.

2020-12-03 10:20 UTC, simonmika requested changes

2020-12-03 10:20 UTC, simonmika commented on Order/Creatable.ts
> +	subscription?: authly.Identifier
Is this needed at all? I imagine orders will always me created with an account payment in these cases. But I'm open for both.

2020-12-03 10:20 UTC, simonmika commented on Schedule/getNext.ts
> +export function getNext(
What about `next` or `due`? `get` is should be superfluous.

2020-12-03 10:20 UTC, simonmika commented on Schedule/getNext.ts
> +function calculateDueHelper(
Rename this as well.

2020-12-03 10:20 UTC, simonmika commented on Payment/Account/Creatable.ts
> +	account?: authly.Identifier // @deprecated
This would then not be deprecated, I guess, depending on `Order.Creatable`.

2020-12-03 10:22 UTC, florianebmeier commented on Schedule/getNext.ts
> +export function getNext(
`next` or `due` are not verbs and break the naming convention. If we decide to break it i would suggest `next`

2020-12-03 10:25 UTC, simonmika commented on Schedule/calculateDue.ts
> +	previousDue?: isoly.DateTime
So then just use it and not use `start`? One should be enough?

2020-12-03 10:25 UTC, simonmika commented on Schedule/getNext.ts
> +export function getNext(
Let's break the naming convention!

2020-12-03 10:26 UTC, florianebmeier commented on Order/Creatable.ts
> +	subscription?: authly.Identifier
Having them on `Order.Creatable` leaves us more room for expanding all types of payments associated to the `account` to orders. It also makes implementation easier, as we do not have to move fields between order and payment in the creation of the order, thus leading to a smaller code base.

2020-12-03 10:26 UTC, simonmika commented on Schedule/getNext.ts
> +function calculateDueHelper(
If we could it would we a property after all.

2020-12-03 10:26 UTC, simonmika commented on Schedule/getNext.ts
> +export function getNext(
If it could be, it would be a property?

2020-12-03 10:29 UTC, simonmika commented on Order/Creatable.ts
> +	subscription?: authly.Identifier
Sure, if that helps.

2020-12-03 10:39 UTC, florianebmeier commented on Schedule/calculateDue.ts
> +	previousDue?: isoly.DateTime
For some cases we need to know if the start is already a due date or not. 
Example:
`frequency:"monthly", offset:1, divisor:2` 
If we set the start date to the 2nd of January, we expect the first due date to be the 1st of February, as it is the next date that fulfills our condition. Then, we want to charge every two month, (April, June etc.).
If we put in the 1st of February in the next iteration, without specifying that this was the previous due date, we will not have the intended outcome.

2020-12-07 15:00 UTC, simonmika requested changes
Just the one issue with Date or DateTime. Let's discuss that.

2020-12-07 15:00 UTC, simonmika commented on Schedule/next.ts
> +export function next(schedule: Frequency | Schedule, previous?: isoly.DateTime): isoly.DateTime {
Both `previous` and the return type should probably be just a date, I guess? If not the time should at least be zero?

2020-12-07 15:05 UTC, florianebmeier commented on Schedule/next.ts
> +export function next(schedule: Frequency | Schedule, previous?: isoly.DateTime): isoly.DateTime {
I guess that is correct. We do not need the hours minutes etc. Do we have an `isoly` Date somewhere? Otherwise we can use translate it to a Date using `.substring(0,10)` which i currently use when i need it.

2020-12-07 15:34 UTC, florianebmeier commented on Schedule/next.ts
> +export function next(schedule: Frequency | Schedule, previous?: isoly.DateTime): isoly.DateTime {
Moved creating `isoly.Date` to its own task.

2020-12-09 12:01 UTC, fredrikbryntesson approved these changes

2020-12-09 12:01 UTC, merged