Balance model changes
payfunc/model pull request #320
Opened 2020-12-10 09:56 UTC by florianebmeier

Added Balance

Balance field in Account

Balance create function

Due Date

2020-12-10 09:59 UTC, simonmika requested changes

2020-12-10 09:59 UTC, simonmika commented on Balance/index.ts
> +export interface Balance extends BalanceCreatable {
Didn't we agree on pushing this into `Account` and call the item list `balance`?

2020-12-10 10:04 UTC, florianebmeier commented on Balance/index.ts
> +export interface Balance extends BalanceCreatable {
I might have forgotten about that. Did we not want to have it because balance should include an item List and a total?
If we want it seperated, do we want to have a balance settings field, which includes the schedule information etc. ?

2020-12-10 10:05 UTC, florianebmeier commented on Balance/index.ts
> +export interface Balance extends BalanceCreatable {
I just picked the solution that was in the original branch we made.

2020-12-10 10:07 UTC, simonmika commented on Balance/index.ts
> +export interface Balance extends BalanceCreatable {
We had a discussion when we where looking at the API-endpoints we where proposing. The model has to reflect the endpoints we have.

2020-12-10 10:10 UTC, simonmika commented on Balance/index.ts
> +export interface Balance extends BalanceCreatable {
Looking at https://github.com/payfunc/backend/issues/735 it reflects what we agreed on. To implement that you will need to change your proposal.

2020-12-11 08:24 UTC, simonmika approved these changes

2020-12-11 11:04 UTC, merged