Class to generate error messages for the user.
payfunc/model pull request #343
Opened 2021-04-16 14:24 UTC by nilssonemma

2021-04-16 15:57 UTC, robinnedergard requested changes
Some added fields for compatibility with future changes also requested.

2021-04-16 15:57 UTC, robinnedergard commented on ErrorMessage/index.ts
> +						case "Card.Token":
add cases for:
`case "verification":`
`case "card.verification":`

2021-04-16 15:57 UTC, robinnedergard commented on ErrorMessage/index.ts
> +								case "Card expired":
Line `case "Card expired":` can be removed now (but keep the correct one containing a dot).

2021-04-16 15:57 UTC, robinnedergard commented on ErrorMessage/index.ts
> +								case "Not enrolled.":
move `case "Not enrolled.":` to it's own case with text: `t("Your card doesn't support required 3-D Secure verification. Please try another card.")` and remember to add translation.

2021-04-16 15:57 UTC, robinnedergard commented on ErrorMessage/index.ts
> +							? t("The card details are incorrect. Please enter valid card details and try again.")
Keep for now, but shouldn't be needed in the future.

2021-04-19 07:16 UTC, robinnedergard requested changes

2021-04-19 07:16 UTC, robinnedergard commented on ErrorMessage/translation/sv.ts
> +	"Your card doesn't support required 3-D Secure verification. Please try another card.":
Noticed different spelling of "3-D Secure" in two other error messages, change all of them to either "3D secure" or "3-D Secure" for consistency.

2021-04-19 07:16 UTC, robinnedergard commented on ErrorMessage/index.ts
> +									message = t("Your card doesn't support required 3-D Secure verification. Please try another card.")
Noticed different spelling of "3-D Secure" in two other error messages, change all of them to either "3D secure" or "3-D Secure" for consistency.

2021-04-19 07:25 UTC, robinnedergard approved these changes

2021-04-20 09:00 UTC, fredrikbryntesson approved these changes

2021-04-20 09:00 UTC, merged