Renamed account and customer.
payfunc/model pull request #358
Opened 2021-06-21 14:24 UTC by marcushanses

- [ ] https://github.com/payfunc/model-base/pull/19

2021-06-21 14:54 UTC, florianebmeier requested changes

2021-06-21 14:54 UTC, florianebmeier commented on Connection.ts
> +	static get cusotmerKeys(): authly.Token[] {
customerKeys

2021-06-21 14:54 UTC, florianebmeier commented on ErrorMessage/translation/sv.ts
> +	"The customer could not be created.": "Kunde inte skapa konto.",
Kunde inte skapa Kund

2021-06-21 14:54 UTC, florianebmeier commented on Order/index.ts
> +			(value.customer == undefined || Contact.is(value.customer) || authly.Identifier.is(value.customerID, 16)) &&
Not customerID

2021-06-21 14:54 UTC, florianebmeier commented on Order/index.ts
> +								Contact.is(value.customer) || { property: "customer", type: "Customer | undefined" },
Flaw is missing case for customer:authly.Identifier

2021-06-21 14:54 UTC, florianebmeier commented on Order/index.ts
> +				new selectively.Type.String("customerID"),
Remove

2021-06-21 14:54 UTC, florianebmeier commented on Order/index.ts
> +		customerID: new selectively.Type.String(),
Remove

2021-06-21 15:18 UTC, florianebmeier approved these changes

2021-06-22 06:24 UTC, nilssonemma requested changes

2021-06-22 06:24 UTC, nilssonemma commented on Customer/Creatable.ts
> +	customer?: Contact
Rename this to contact?

2021-06-22 07:56 UTC, Magnus93 commented on Order/Creatable.ts
> +							value.customer == undefined || Contact.is(value.customer) || Contact.flaw(value.customer),
Flaw is missing for customer is of type authly.Identifier

2021-06-22 12:01 UTC, Magnus93 commented on Customer/Creatable.ts
Remove empty row

2021-06-22 14:28 UTC, florianebmeier approved these changes

2021-06-22 21:45 UTC, fredrikbryntesson approved these changes

2021-06-22 21:46 UTC, merged