Added category property to Payment
payfunc/model pull request #361
Opened 2021-06-23 11:44 UTC by nilssonemma

2021-06-23 15:57 UTC, florianebmeier requested changes

2021-06-23 15:57 UTC, florianebmeier commented on Payment/Base.ts
> +	category?: "purchase" | "withdrawal"
I believe this should be on the order / creatable, not the Payment

2021-06-24 09:03 UTC, robinnedergard approved these changes

2021-06-24 09:54 UTC, fredrikbryntesson approved these changes

2021-06-24 09:54 UTC, merged