PSP Client
payfunc/model pull request #375
Opened 2021-08-23 14:12 UTC by Magnus93

2021-08-23 14:50 UTC, nilssonemma requested changes

2021-08-23 14:50 UTC, nilssonemma commented on Client/Customer.ts
> +		return await this.connection.remove<undefined>(`customer${customer}/subscription/${subscription}`)
You forgot the "/" after customer (also change undefined to the correct return type)

2021-08-23 14:50 UTC, nilssonemma commented on Client/Customer.ts
> +		return await this.connection.post<gracely.Result>(`customer/${customer}/balance`, request)
Should be await this.connection.post<gracely.Result | gracely.Error>
Add gracely.Error in the functions below too

2021-08-24 09:39 UTC, Magnus93 commented on Client/Customer.ts
> +		return await this.connection.post<gracely.Result>(`customer/${customer}/balance`, request)
Nope, specifying gracely.Error is not necessary
https://github.com/payfunc/model-base/blob/master/Connection.ts#L33

2021-08-24 13:57 UTC, marcushanses approved these changes

2021-08-24 13:57 UTC, marcushanses commented on Client/Customer.ts
> +		return await this.connection.post<string>(`customer/${customer}`, undefined)
why undefined?

2021-08-24 13:57 UTC, marcushanses commented on Client/Customer.ts
> +		return await this.connection.post<ModelCustomer.Link>(`customer/${customer}/link`, undefined)
why undefined?

2021-08-30 07:25 UTC, nilssonemma approved these changes

2021-08-30 11:21 UTC, fredrikbryntesson approved these changes

2021-08-30 11:21 UTC, merged