Me client
payfunc/model pull request #384
Opened 2021-08-31 09:47 UTC by marcushanses

2021-08-31 15:50 UTC, nilssonemma approved these changes

2021-09-01 07:27 UTC, Magnus93 approved these changes

2021-09-01 13:16 UTC, Magnus93 approved these changes

2021-09-07 15:32 UTC, nilssonemma submitted a review, later dismissed

2021-09-07 15:56 UTC, Magnus93 requested changes

2021-09-07 15:56 UTC, Magnus93 commented on Customer/index.ts
> +		export function getStatus(customer: Customer, order?: Order): Status {
`Status.getStatus` is not nice. Should maybe be changed `Status.get`

2021-09-08 06:43 UTC, nilssonemma approved these changes

2021-09-08 06:51 UTC, Magnus93 commented on PaymentVerifier/index.ts
> +	abstract verify(
Should this not be async since it returns a Promise?

2021-09-08 06:57 UTC, Magnus93 commented on PaymentVerifier/index.ts
>  export abstract class PaymentVerifier {
Why have a seperate PaymentVerifier class and namespace? Why not just have namespace?

2021-09-08 07:10 UTC, Magnus93 submitted a review, later dismissed

2021-09-08 14:51 UTC, robinnedergard submitted a review, later dismissed

2021-09-09 13:08 UTC, fredrikbryntesson approved these changes

2021-09-09 13:08 UTC, merged